## Pandas는 데이터 분석을 위한 라이브러리로 데이터를 효과적으로 처리하고, 보여줄 수 있는 다양한 기능을 제공합니다.
### 특히 tabular data를 다루는데 특화되어 있습니다. (excel과 유사한 기능을 제공합니다. 그럼 excel을 쓰면 안되나? 싶지만 대용량 데이터를 다루기에 excel은 그다지 적절한 도구가 아닙니다.)

In [15]:
# !pip install pandas
import pandas as pd # pandas library를 import합니다. as ~ 뒤에 있는 것은 ilias로 pandas를 줄여서 부르는 표현입니다.

### Pandas의 주요 데이터 구조
1. Series : 1차원 배열
2. DataFrame : 2차원 배열

In [16]:
# Series
s = pd.Series([1, 3, 5, 7, 9])
print(s)
# change index
s = pd.Series([1, 3, 5, 7, 9], index=['a', 'b', 'c', 'd', 'e'])
print(s)
s["a"]

0    1
1    3
2    5
3    7
4    9
dtype: int64
a    1
b    3
c    5
d    7
e    9
dtype: int64

np.int64(1)

In [ ]:
# DataFrame
df = pd.DataFrame({
    'name': ['A', 'B', 'C', 'D', 'E'],
    'age': [10, 20, 30, 40, 50],
    'score': [100, 200, 300, 400, 500]
})

df

  name  age  score
0    A   10    100
1    B   20    200
2    C   30    300
3    D   40    400
4    E   50    500

In [ ]:
# DataFrame의 column 선택
df['name']
df.name

0    A
1    B
2    C
3    D
4    E
Name: name, dtype: object

In [ ]:
# DataFrame의 row 선택
df.loc[0]

name       A
age       10
score    100
Name: 0, dtype: object

In [ ]:
## 이렇게 특정 행, 또는 열을 선택한 결과는 Series로 반환됩니다.

# DataFrame의 특정 column의 특정 row 선택
df['name'][0]
df.iloc[0, 0]

'A'

In [ ]:
# Datafrane의 특정 구역 선택
df.iloc[0:2, 0:2]

  name  age
0    A   10
1    B   20

# Dataframe을 만드는 다양한 방법
## 1. list로 만들기
## 2. dictionary로 만들기
## 3. *csv 파일로 부터 읽어오기*

In [ ]:
# dictionary로 만들기
dict1 = {
    'name' : {0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E'},
    'age' : {0: 10, 1: 20, 2: 30, 3: 40, 4: 50},
    'score' : {0: 100, 1: 200, 2: 300, 3: 400, 4: 500}
}
df = pd.DataFrame(dict1)
print(df)

  name  age  score
0    A   10    100
1    B   20    200
2    C   30    300
3    D   40    400
4    E   50    500

In [ ]:
# csv 저장하고 불러오기
df.to_csv("test.csv", index=False, encoding='cp949') # 위에서 만든 DataFrame을 csv 파일로 저장합니다. index=False는 index를 저장하지 않겠다는 의미입니다.
df.to_csv("test_index.csv", index=True, encoding='cp949') # index를 저장하겠다는 의미입니다.

In [ ]:
df = pd.read_csv("test.csv", encoding='cp949') # 경로에 있는 csv file을 읽어와 Dataframe을 만드는 코드입니다.
df_index = pd.read_csv("test_index.csv", encoding='cp949') # 여기서 경로란 현재 작업중인 directory를 의미합니다. 즉 현재 작업중인 directory에 test.csv 파일이 있어야 합니다.

# Dataframe 조작
## 1. column 추가
## 2. column 삭제
## 3. row 추가
## 4. row 삭제
## 5. column 값 변경
## 6. row 값 변경
## 7. column 순서 변경
## 8. index 변경
## 9. sorting
## 10. banding을 통한 column 값 변경

In [ ]:
df = pd.read_csv("test.csv")

df

  name  age  score
0    A   10    100
1    B   20    200
2    C   30    300
3    D   40    400
4    E   50    500

In [ ]:
# 1. column 추가
df['ID'] = [1, 2, 3, 4, 5]
df

  name  age  score  ID
0    A   10    100   1
1    B   20    200   2
2    C   30    300   3
3    D   40    400   4
4    E   50    500   5

In [ ]:
# 2. column 삭제
df_2 = df.drop('ID', axis=1, inplace=False) # axis=1은 column을 의미합니다. inplace=True는 원본을 변경하겠다는 의미입니다.
df_2
df

  name  age  score  ID
0    A   10    100   1
1    B   20    200   2
2    C   30    300   3
3    D   40    400   4
4    E   50    500   5

In [ ]:
# 3. row 추가
df.loc[5] = ['F', 60, 600, 6]
df

In [ ]:
# 4. row 삭제
df.drop(5, axis=0, inplace=True) # axis=0은 row를 의미합니다.
df

In [ ]:
# 5. column 값 변경
df['age'] = df['age'] + 10
df

In [ ]:
# 6. row 값 변경
df.loc[0] = ['A', 10, 100, 2]
df

In [ ]:
# ## 그럼 Dataframe의 특정 행, 열의 값을 바꿀 수도 있을까요?
# Hint는 특정 행렬 값을 출력하는 코드를 참고하시는 것입니다.

df.iloc[0, 1] = 20
df

In [ ]:
df = pd.DataFrame({
    'name': ['노서준', '이채원', '김정민', '진서율', '박연서'],
    'age': [25, 23, 21, 26, 24],
    'score': [90, 89, 94, 85, 87],
    'ID': [123, 111, 134, 115, 147],
    'gender': ['남자','여자', '여자', '여자', '남자']
})
df

In [ ]:
# 7. column 순서 변경
df = df[["ID", "name", "age", "score", "gender"]]
df

In [ ]:
# 8. index 변경
df.set_index('ID', inplace=True)
df

In [ ]:
# 9. sorting
# sort by index
df.sort_index()
# sort by column
df.sort_values(by='age', ascending=False)

In [ ]:
# 10. banding을 통한 column 값 변경
df['grade'] = df['score'].apply(lambda x: 'A' if x >= 90 else 'B' if x >= 80 else 'C' if x >= 70 else 'D' if x >= 60 else 'F')
df

# Dataframe의 정보 확인
### 이제 Dataframe 과 조금은 친해지셨나요? 그럼 dataframe을 어떻게 살펴보는지 알아봅시다.

In [ ]:
df.head(2)
df.tail(2) # 우선 데이터가 어떤 column으로 구성되어 있는지를 파악해야압니다. head와 tail을 통해 데이터의 일부를 살펴볼 수 있습니다.

In [ ]:
df.describe() # index를 제외한 수치정보(numeric)들에 대한 통계치를 보여줍니다..!

In [ ]:
df.info() # 데이터프레임의 정보를 보여줍니다. 데이터 타입, null값 여부 등을 확인할 수 있습니다. 이렇게 전반적인 통계치를 확인하고 시작하는 것은 아주 좋은 습관입니다 :)

## 다양한 통계치 함수
### count : 전체 row의 개수를 반환합니다.
### mean : 평균을 반환합니다.
### std : 표준편차를 반환합니다.
### min : 최소값을 반환합니다.
### max : 최대값을 반환합니다.
### 25%, 50%, 75% : 백분위수를 반환합니다.

In [ ]:
df['age'].count() # age column의 전체 row의 개수를 반환합니다.
df['age'].mean() # age column의 평균을 반환합니다.
df['age'].std() # age column의 표준편차를 반환합니다.
df['age'].min() # age column의 최소값을 반환합니다.
df['age'].max() # age column의 최대값을 반환합니다.
df['age'].quantile(0.25) # age column의 25% 백분위수를 반환합니다.
df['age'].quantile(0.5) # age column의 50% 백분위수를 반환합니다.
df['age'].quantile(0.75) # age column의 75% 백분위수를 반환합니다.

# 이처럼 통계 함수를 통해 데이터의 전반적인 특징을 살펴볼 수 있습니다!
# 근데 이 방법은 너무 포괄적이라 세부적인 통계치를 확인하기 어렵습니다. 그래서 다음에는 groupby를 통해 세부적인 통계치를 확인하는 방법을 알아보겠습니다.

## Groupby
### Groupby는 SQL의 groupby와 유사한 기능을 제공합니다.
### 특정 column을 기준으로 그룹을 지어 그룹별로 통계치를 확인할 수 있습니다.
### * groupby 함수는 단독으로 쓰이기 보단 뒤에 통계치를 확인하는 다양한 함수와 함께 쓰입니다! *
### df.groupby('column_name').function() << 이런식으로 쓰입니다!

In [ ]:
# 예를들어 설별을 기준으로 그룹을 평균을 확인해보려면 어떻게 하면 될까요?
grouped_gender = df.groupby('gender')[['score', 'age']].mean()

grouped_gender

In [ ]:
grouped_gender_grade = df.groupby(['gender', 'grade'])['score'].mean()

grouped_gender_grade